name: Push to Docker Hub
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: log in to Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: paxxs/wordpress-env:latest

